// @ts-check
const path = require('node:path');

const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const boundaries = /** @type {import('eslint').ESLint.Plugin} */ (
  require('eslint-plugin-boundaries')
);
const tailwindcss = /** @type {import('eslint').ESLint.Plugin} */ (
  /** @type {unknown} */ (require('eslint-plugin-tailwindcss'))
);
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');

module.exports = defineConfig([
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    plugins: {
      boundaries,
    },
    settings: {
      'boundaries/root-path': __dirname,
      'boundaries/elements': [
        {
          type: 'docs',
          pattern: 'projects/docs/src',
          partialMatch: false,
        },
        {
          type: 'electron-renderer',
          pattern: 'projects/electron/src',
          partialMatch: false,
        },
        {
          type: 'electron-main',
          pattern: 'projects/electron/electron',
          partialMatch: false,
        },
      ],
      'import/resolver': {
        typescript: {
          project: './tsconfig.json',
        },
      },
    },
    rules: {
      'boundaries/dependencies': [
        'error',
        {
          default: 'disallow',
          checkAllOrigins: false,
          checkUnknownLocals: false,
          checkInternals: false,
          policies: [
            {
              from: {
                element: {
                  type: 'electron-main',
                },
              },
              allow: {
                to: {
                  element: {
                    type: 'electron-renderer',
                    fileInternalPath: 'app/core/qdb-contracts.ts',
                  },
                },
              },
            },
          ],
        },
      ],
      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: 'app',
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: 'element',
          prefix: 'app',
          style: 'kebab-case',
        },
      ],
      '@angular-eslint/sort-keys-in-type-decorator': 'error',
      '@angular-eslint/prefer-output-readonly': 'error',
      '@angular-eslint/prefer-on-push-component-change-detection': 'error',
      '@angular-eslint/prefer-standalone': 'error',
      '@angular-eslint/prefer-signals': 'error',
      '@angular-eslint/prefer-signal-model': 'error',
      '@angular-eslint/component-max-inline-declarations': ['error', { template: 10, styles: 0 }],
      '@angular-eslint/inject-at-top': 'error',
      'no-unused-private-class-members': 'off',
      '@typescript-eslint/no-unused-private-class-members': 'error',
      'max-lines': ['error', { max: 500, skipBlankLines: false, skipComments: false }],
    },
  },
  {
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {
      '@angular-eslint/template/prefer-self-closing-tags': 'error',
      '@angular-eslint/template/prefer-control-flow': 'error',
      '@angular-eslint/template/prefer-at-else': 'error',
      '@angular-eslint/template/prefer-at-empty': 'error',
      '@angular-eslint/template/button-has-type': 'error',
      '@angular-eslint/template/attributes-order': 'error',
      '@angular-eslint/template/no-any': 'error',
      '@angular-eslint/template/prefer-contextual-for-variables': 'error',
      'no-restricted-syntax': [
        'error',
        {
          selector: 'Call[args.length > 0]:not(BoundEvent Call)',
          message:
            'Avoid calling functions with arguments in templates. Use signals or properties instead.',
        },
      ],
      'max-lines': ['error', { max: 500, skipBlankLines: false, skipComments: false }],
    },
  },
  {
    files: ['projects/electron/src/app/core/country-flag/generated-flags.ts'],
    rules: {
      'max-lines': 'off',
    },
  },
  {
    files: ['**/*.spec.ts'],
    rules: {
      'max-lines': ['error', { max: 800, skipBlankLines: false, skipComments: false }],
    },
  },
  {
    files: ['**/electron/database.ts'],
    rules: {
      'max-lines': ['error', { max: 900, skipBlankLines: false, skipComments: false }],
    },
  },
  {
    files: ['**/electron/importer.ts'],
    rules: {
      'max-lines': ['error', { max: 2200, skipBlankLines: false, skipComments: false }],
    },
  },
  {
    files: ['**/*.ts', '**/*.html'],
    plugins: {
      tailwindcss,
    },
    settings: {
      tailwindcss: /** @type {import('eslint-plugin-tailwindcss').PluginSettings} */ ({
        cssConfigPath: path.join(__dirname, 'projects/electron/src/tailwind.css'),
      }),
    },
    rules: {
      'tailwindcss/classnames-order': 'error',
      'tailwindcss/enforces-negative-arbitrary-values': 'error',
      'tailwindcss/enforces-shorthand': 'error',
      'tailwindcss/important-modifier-suffix': 'error',
      'tailwindcss/no-arbitrary-value': 'error',
      'tailwindcss/no-contradicting-classname': 'error',
      'tailwindcss/no-custom-classname': [
        'warn',
        {
          whitelist: [
            'about-header',
            'app-content',
            'app-page-header',
            'attribute-group',
            'attribute-groups',
            'attribute-list',
            'attribute-tile',
            'brand',
            'browse-tile',
            'choice-label',
            'close-button',
            'code-card',
            'column-button',
            'column-count',
            'column-drag-preview',
            'column-fields',
            'column-form',
            'column-layouts',
            'column-layouts-icon',
            'column-list',
            'column-row',
            'column-tab-actions',
            'column-tab-content',
            'compact',
            'compatibility-error',
            'confetti-canvas',
            'content-shell',
            'context-banner',
            'country-line',
            'country-with-flag',
            'danger',
            'danger-card',
            'database-date',
            'database-grid',
            'database-icon',
            'database-kind',
            'database-summary',
            'description',
            'detail-header',
            'details-fields',
            'documentation-label',
            'drag-handle',
            'drawer-footer',
            'drawer-header',
            'empty-preview',
            'entity-link',
            'entity-search',
            'entity-shell',
            'entity-topbar',
            'error',
            'eyebrow',
            'filter-button',
            'filter-content',
            'filter-count',
            'filter-drawer',
            'filter-fields',
            'filter-note',
            'filter-with-hint',
            'finder-column-tabs',
            'footer-inner',
            'footer-links',
            'format-options',
            'identity',
            'import-progress',
            'import-summary',
            'issue-section',
            'lead',
            'league-list',
            'league-row',
            'legal',
            'live-announcement',
            'loading',
            'message',
            'metric-grid',
            'nationality',
            'nationality-with-flag',
            'navigation-heading',
            'navigation-trigger',
            'note',
            'omitted',
            'option-content',
            'original-id',
            'overview-tab',
            'page-heading',
            'player-link',
            'player-name',
            'position-list',
            'position-matrix',
            'position-matrix-row',
            'position-rating',
            'preview-list',
            'preview-row',
            'primary-navigation-link',
            'profile-grid',
            'qdb-wizard',
            'range',
            'raw-fields',
            'remove-database',
            'reputation-star',
            'reputation-stars',
            'reputation-tile',
            'reputation-value',
            'reset-layouts',
            'reset-layouts-icon',
            'result-actions',
            'result-count',
            'result-header',
            'results',
            'samples',
            'scroll-to-top',
            'search',
            'section-heading',
            'section-icon',
            'section-links',
            'settings-card',
            'shell',
            'site-header',
            'skip-link',
            'source-fields',
            'source-picker',
            'source-status',
            'source-summary',
            'state',
            'step-actions',
            'step-content',
            'success',
            'summary',
            'table-scroll',
            'team-row',
            'theme-options',
            'tile-grid',
            'tile-icon',
            'toolbar-spacer',
            'topbar',
            'utility-actions',
            'validation-report',
            'version',
            'warnings',
            'wizard-card',
          ],
        },
      ],
      'tailwindcss/no-unnecessary-arbitrary-value': 'error',
    },
  },
]);
